# Lecture 2_3: The Wright-Fisher Model

## Example 2.11
**1. Find the stationary distribution of the WF model with mutation given $u=v=0.05$ & $N=6$.**

From last lecture we have

In [1]:
import numpy as np

def wright_fisher_mu_transition_matrix(N,u,v):
    """
    Generate the transition probability matrix for the Wright-Fisher model.

    Parameters:
    - N: Population size
    - u: mutation rate from 'A'->'a'
    - v: mutation rate from 'a'->'A'

    Returns:
    - P: Transition probability matrix
    """

    P = np.zeros((N+1, N+1)) #Matrix of 0s

    for i in range(N+1):
        for j in range(N+1):
            x=i/N*(1-u)+(1 - i/N)*v
            y=i/N*(u)+(1 - i/N)*(1-v)
            P[i, j] = (np.math.comb(N, j) * (x ** j) * (y ** (N - j)))

    return P

In [38]:
t_matrix=wright_fisher_mu_transition_matrix(6,0.05,0.05)

We have to obtain the eigensystem:

In [39]:
eigenvalues, eigenvectors = np.linalg.eig(t_matrix)
print(eigenvalues)

[1.         0.9        0.675      0.405      0.18225    0.054675
 0.00820125]


Note taht eigevectors here is a matrix where each column is an eigenvector. I.e. it is the matrix $A$ in $A.D.A^{-1}$

In [40]:
eigenvectors[:,0]

array([0.37796447, 0.37796447, 0.37796447, 0.37796447, 0.37796447,
       0.37796447, 0.37796447])

In [41]:
t_matrix@eigenvectors[:,0]

array([0.37796447, 0.37796447, 0.37796447, 0.37796447, 0.37796447,
       0.37796447, 0.37796447])

The eigenvectors above are the left eigenvectors, we want the right eigenvectors (i.e., the rows of $A^{-1}$):

In [42]:
rightEVs=np.linalg.inv(eigenvectors);

In [43]:
rightEVs[0]@t_matrix

array([0.47820931, 0.37065865, 0.31906156, 0.30989228, 0.31906156,
       0.37065865, 0.47820931])

The probabilities have to sum to $1$ so we normalize the length of the eigevector in this fashion.

In [44]:
rightEVs[0]/np.sum(rightEVs[0])

array([0.18074613, 0.1400958 , 0.12059393, 0.11712827, 0.12059393,
       0.1400958 , 0.18074613])

This says that the probability that the allele is in $0,1,2,\dots N$ copies after a loooong time is approximately equal.

**2. Repeat this for  $u=v=0.005$.**

In [45]:
t_matrix=wright_fisher_mu_transition_matrix(6,0.005,0.005)
eigenvalues, eigenvectors = np.linalg.eig(t_matrix)
rightEVs=np.linalg.inv(eigenvectors);
rightEVs[0]/np.sum(rightEVs[0])

array([0.43767708, 0.03348106, 0.01975149, 0.01818075, 0.01975149,
       0.03348106, 0.43767708])