# Lecture 2_1: Transition Probability Matricies

## Matrix Multiplication

We start by inputting our transition probability matrix.

In [3]:
import numpy as np
# Transition probability matrix
matrix_a = np.array([[0.7, 0.3,0], [0.4, 0.5,0.1],[0,0.3,0.7]])
#Initial state vector
vec_v=[[0,1,0]]
print(matrix_a)
print(vec_v)

[[0.7 0.3 0. ]
 [0.4 0.5 0.1]
 [0.  0.3 0.7]]
[[0, 1, 0]]


Let's first discuss matrix opperations that we will be using:
We perform **matrix multiplication** by taking the dot product

In [3]:
np.dot(matrix_a, matrix_a)

array([[0.61, 0.36, 0.03],
       [0.48, 0.4 , 0.12],
       [0.12, 0.36, 0.52]])

We will be doing a lot of matrix multiplication in this course so we may want to use the shortcut of an @ sign

In [12]:
matrix_a2=matrix_a @ matrix_a
print(matrix_a2)

[[0.61 0.36 0.03]
 [0.48 0.4  0.12]
 [0.12 0.36 0.52]]


In [10]:
matrix_a3=matrix_a @ matrix_a @ matrix_a
print(matrix_a3)

[[0.571 0.372 0.057]
 [0.496 0.38  0.124]
 [0.228 0.372 0.4  ]]


We can take the power of a matrix by:

In [12]:
from numpy.linalg import matrix_power
matrix_power(matrix_a, 3)

array([[0.571, 0.372, 0.057],
       [0.496, 0.38 , 0.124],
       [0.228, 0.372, 0.4  ]])

We can multiply a matrix by a row vector on the left by:

In [18]:
vec_v1=vec_v @ matrix_a
print(vec_v1)

[[0.4 0.5 0.1]]


Note that we can't multiply on the right.

In [2]:
matrix_a @ vec_v

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

## Example 2.3: Ecological State 

In [4]:
# Transition probability matrix
matrix_a = np.array([[0.7, 0.3,0], [0.4, 0.5,0.1],[0,0.3,0.7]])
#Initial state vector
vec_v=[[0,1,0]]

1. **Given the state vector (vec_v) and transition matrix (matrix_a), what is the probability that an ecosystem where both species currently coexists has only one species 2 years later, how about 3 years later?**

Let's look at next year first by multiplying:

$$
\vec{V}(1)=\vec{V}(0).\mathbf{P}
$$

In [7]:
vec_v1=vec_v@matrix_a
print(vec_v1)

[[0.4 0.5 0.1]]


This tells us that next year 40% of habitats will have only species A, 10% will only have species B, and 50% will have co-existence.

We can get year two by:

$$
\vec{V}(2)=\vec{V}(1).\mathbf{P}
$$

In [9]:
vec_v2=vec_v1@matrix_a
print(vec_v2)

[[0.48 0.4  0.12]]


The proportion of species A only and species B only have increased, the amount of coexietence has decreased.  Note we would have gotten the same answer by using a matirx power.

$$
\vec{V}(2)=\vec{V}(0).\mathbf{P}^2
$$

In [21]:
vec_v@matrix_power(matrix_a, 2)
#Saving the value of the matrix
matrix_a2=matrix_power(matrix_a, 2)

This is also more convenient as the number of generations increases:

In [15]:
vec_v3=vec_v@matrix_power(matrix_a, 3)
#Saving the value of the matrix
matrix_a3=matrix_power(matrix_a, 3)
print(vec_v3)

[[0.496 0.38  0.124]]


**2. Use the Chapman-Kolmogorov equation to calculate the probability of being in state 1 (species A only) in 5 years.**

We have the 2-step matrix (matrix_a2) and the three step matrix (matrix_a3), given that we started in state 2 (see initial vector), we can calculate the probability of being in state 1 after generation 5 by:

$$
\Pr(X_5=2)=\sum_k p^{(2)}_{2,k}p^{(3)}_{k,1}
$$

**important note** Python indexes from 0, which means we want to sum over the '1' row of $P^2$ and the '0' column of $P^3$

In [23]:
np.sum(matrix_a2[1, :]*matrix_a3[ :,0])

0.12495999999999999

Checking our answer using matrix powers:

In [25]:
vec_v@matrix_power(matrix_a, 5)

array([[0.49984, 0.3752 , 0.12496]])